version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-ecovoluntario
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecovoluntario-db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local
